### ISSUE TITLE
Issue with Sklearn

### ISSUE THREAD

**Issue by Barbany** [bigpon/vcc20_baseline_cyclevae#1]
Your requirements don't specify a version of scikit-learn. In particular I have the version 0.23.1 and your use of the [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) function in the script `src/parallel_wavegan/datasets/audio_world_dataset.py` is not (no longer?) allowed.

The following message appears:
```
RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?
```
which happens because you manually set the mean and scale for the transformation. I didn't found a workaround with the same function; it seems that it needs to be set with a fit on some data (see example on documentation).

However it's enough to change the last lines of the constructor of `AudioWorldDataset` by
```python
mean  = read_hdf5(stats, mean_path)
scale = read_hdf5(stats, scale_path)
self.feat_transform = lambda x: (x - mean) / scale
```

**Comment by bigpon** [comment]
Thanks for your suggestion!
However, I updated it followed the original PWG implementation as follows.
[(https://github.com/kan-bayashi/ParallelWaveGAN/commit/66ecc393ecadf957539779557582627f5dcbba11](https://github.com/kan-bayashi/ParallelWaveGAN/commit/66ecc393ecadf957539779557582627f5dcbba11)
Your method also works well.
Thank you very much.
