### ISSUE TITLE
Which data set should I use

### ISSUE THREAD

**Issue by user-ZJ** [bigpon/vcc20_baseline_cyclevae#5]
Hi I want to rerun your code, but I have some questions.

At baseline readme.md:
```
Then, move to the experiment directory, and copy the waveform data of VCC 2020 to wav_24kHz folder.
$ cd ../egs/cyclevae
$ cp -r <path_to_vcc2020_data>/* wav_24kHz
```

At the main readme.md,have there dataset:
```
2020/4/17 upload the missed conversion pair of SEF2-TEM1 of reference_v.10.

2020/3/18 release the generated samples of reference_v.10.

2020/3/11 release the first version repo and the generated samples of development set (dv50_vcc2020_24kHz).
```

My question is Which data set should I use. thanks!

**Comment by bigpon** [comment]
Hi ZJ, 
We trained our models based on the Voice Conversion Challenge 2020 corpus.
However, the organizers haven't publically released the corpus now (They have released VCC2018 and VCC2016).
Maybe you can contact the organizers to access the corpus.
The website of VCC2020 is the following,
http://www.vc-challenge.org/
or you may try VCC2018 corpus first.
https://datashare.is.ed.ac.uk/handle/10283/3061

**Comment by user-ZJ** [comment]
@bigpon Could  you share the data you got, thanks!
I just want to reproduce "Baseline System of Voice Conversion Challenge 2020 with Cyclic Variational
Autoencoder and ParallelWaveGAN" paper

**Comment by bigpon** [comment]
Hi ZJ,
I'm sorry that we should follow the schedule of the VCC20 organizers.
We cannot release the VCC20 corpus by ourselves.
I suggest that contacting the organizers for requiring the corpus.

**Comment by user-ZJ** [comment]
thanks
